import os
import arcpy

# BACKUP OLD DATA WITH DATE ATTACHED. 




# INPUT NEW DATA FOLDER LOCATION


# CREATE NEW GDB


# REPROJECT ALL LAYERS USING SPECIAL TRANSLATION, INTO NEW GDB.




# FLOOD HAZARD AREA: SELECT ALL, DELETE, COPY/PASTE IN NEW DATA.  SAVE EDITS.


# BFE'S: SELECT ALL, DELETE, COPY/PASTE IN NEW DATA.  SAVE EDITS.


# CROSS SECTIONS: SELECT ALL, DELETE, COPY/PASTE IN NEW DATA.  SAVE EDITS.
